### ISSUE TITLE
runtimepath not displayed correctly

### ISSUE THREAD

**Issue by prabirshrestha** [equalsraf/neovim-qt#18]
Not a big problem since it correctly loads the runtime files.

`_nvimrc` file:

```vimrc
set runtimepath+='C:/Program Files/NEOVIM/share/nvim/runtime'
```

`set runtimepath?`

![image](https://cloud.githubusercontent.com/assets/287744/7669053/f4bd5f30-fc12-11e4-8992-5216c51772c3.png)

Notice how the full runtimepath isn't shown. It stops at space.

**Comment by Shougo** [comment]
@prabirshrestha You don't add quotes and you must escape spaces.

```vim
set runtimepath+=C:/Program\ Files/NEOVIM/share/nvim/runtime
```

**Comment by prabirshrestha** [comment]
didn't seem to work for me. using quotes or using `\`.

just landed up comping the entire runtime folder to the same location as `nvim-qt.exe`

**Comment by Shougo** [comment]
Hmmm...
You should read `:help option-backslash`.

**Comment by Shougo** [comment]
> didn't seem to work for me. using quotes or using \.

Really?  I tested it and it works for me.

**Comment by prabirshrestha** [comment]
I mean `set runtimepath?` now works. But doesn't seem to load the syntax files correctly. I guess I'm missing some other config?

![image](https://cloud.githubusercontent.com/assets/287744/7669453/1a84d9da-fc29-11e4-9adc-069402bca569.png)

Here is what I get when executing `:syntax enable`. RelWithDebInfo is the folder where the nvim-qt.exe is located.

![image](https://cloud.githubusercontent.com/assets/287744/7669462/56d50306-fc29-11e4-8255-e946210ff4f6.png)

**Comment by Shougo** [comment]
@prabirshrestha You must set runtimepath before executing `:syntax enable`.
And you should check `C:/Program Files/NEOVIM/share/nvim/runtime`.
The runtime files are installed correctly?

**Comment by prabirshrestha** [comment]
runtimepath is in `~/_nvimrc`

```vimrc
set runtimepath+=C:/Program\ Files/NEOVIM/share/nvim/runtime
```

I manually enable syntax so it does run after the runtime is set. `runtime` folders contains all the files from the neovim runtime folder.

![image](https://cloud.githubusercontent.com/assets/287744/7669501/fc14cbca-fc2a-11e4-9099-f9db09cff9b8.png)

`:help` also doesn't seem to work.

![image](https://cloud.githubusercontent.com/assets/287744/7669505/248b3ee0-fc2b-11e4-9152-de1b248e1d87.png)

**Comment by Shougo** [comment]
You should check `runtimepath` by globpath().

`:echo globpath(&runtimepath, 'doc/eval.txt')`

**Comment by prabirshrestha** [comment]
Seems to show the path correctly.

![image](https://cloud.githubusercontent.com/assets/287744/7669543/6870e5f0-fc2c-11e4-9b23-6dd6432727da.png)

**Comment by Shougo** [comment]
Hmmmm...
It is strange behavior.  I give up.

**Comment by equalsraf** [comment]
Cheers @prabirshrestha, can you

`echo $VIMRUNTIMEPATH`

`:version`

The helptags are generated on the install step, that is why they are missing. I should have that fixed in a bit.

**Comment by equalsraf** [comment]
As for the other issue, `syntax on` runs `so $VIMRUNTIME\syntax\syntax.vim` (syntax.c syn_cmd_onoff()) so your rtp does not work there. Which is strange, but seems to be the default behaviour even in Vim.

I have pushed a commit into Appveyor that should help with the helptags and the VIMRUNTIME (still building).

**Comment by prabirshrestha** [comment]
`:echo $VIMRUNTIMEPATH` return empty because I haven't set the runtimepath as an environment variable. If I do set it will it affect my normal vim as I want to be able to run vim and nvim side by side.

![image](https://cloud.githubusercontent.com/assets/287744/7671400/438c2cd4-fc83-11e4-8d4a-864dc433097e.png)

Side note: It would be good to support `nvim-qt --version`. `gvim --version` show a dialog with version info which allows to easily copy the version.

**Comment by equalsraf** [comment]
> :echo $VIMRUNTIMEPATH

Up sorry I meant :echo $VIMRUNTIME (it should print something even if you have not set it). Can you try with one of today's builds?

**Comment by equalsraf** [comment]
Also, in the latest build you should not need to set rtp, it should pick it up from the current location of the nvim.exe. Just uncompress the zip into any folder.

**Comment by prabirshrestha** [comment]
` :echo $VIMRUNTIME` works properly.

Tried the latest build without setting the runtime and syntax enable works too but `:help` doesn't seem to work. I still get the same error for help.

Here is the version I'm using.

![image](https://cloud.githubusercontent.com/assets/287744/7718442/ffdae352-fe64-11e4-968d-4b4b2e42a8e2.png)

**Comment by equalsraf** [comment]
Help should work now https://ci.appveyor.com/project/neovim/neovim/build/226/job/vv53ooermlk095v5/artifacts

**Comment by prabirshrestha** [comment]
works. Thanks.
