### ISSUE TITLE
`p` always pastes another newline

### ISSUE THREAD

**Issue by Ploppz** [equalsraf/neovim-qt#218]
When trying to paste something without newlines into a Visual section, it is always just pasted on a new line after the current. When pasting a whole line, there's always an extra empty line at the end.

**Comment by equalsraf** [comment]
Pasting should be handled by neovim, not the GUI.

Are you by any chance running an older Neovim on windows? There was a similar issue in neovim/neovim.

**Comment by xtal8** [comment]
I can reproduce this on Windows 10 with Neovim 0.2. It's happening when I use `'clipboard'` with `'unnamed'` or `'unnamedplus'` options and  when I paste something from those registers directly with `"*p` or `"+p`.

**Comment by justinmk** [comment]
@xtal8 Where did you get the neovim and neovim-qt builds from? (Please give the exact URL)

**Comment by xtal8** [comment]
@justinmk 
From installation guide on Neovim's Wiki
https://ci.appveyor.com/api/projects/neovim/neovim/artifacts/build/Neovim.zip?branch=master&job=Configuration%3A%20MINGW_32

**Comment by justinmk** [comment]
Confirmed.

**Comment by equalsraf** [comment]
Should be fixed in https://github.com/neovim/neovim/pull/6255

ping @xelra

**Comment by xelra** [comment]
Works flawlessly.

Thanks @equalsraf. It's amazing at which speed you close issues.

**Comment by equalsraf** [comment]
This was actually fixed earlier in win32yank, but I forgot to tag it :S

Closing this one.

**Comment by jorgeOmurillo** [comment]
I'm on Windows 7 (32-bit), I replaced the old win32yank.exe file with v0.0.3 and I still can't copy/paste to the system clipboard.
I used this Neovim build:
https://ci.appveyor.com/api/projects/neovim/neovim/artifacts/build/Neovim.zip?branch=master&job=Configuration%3A%20MINGW_32

If my init.vim file is empty, when I paste text "<S-Insert>" is inserted instead.
