### ISSUE TITLE
[KDE] Alt is hijacked by tabline

### ISSUE THREAD

**Issue by qwfy** [equalsraf/neovim-qt#357]
If you have a `<Alt-SomeKey>` mapping, say `noremap <A-d> <ESC>:bd!<CR>`, then if you have a file whose name begins with a `d`, and you are currently not at that document, then `<A-d>` would be hijacked by the tabline and bring you to that `d` document, and no longer do the desired `:bd!`.

Can we disable this hijacking behaviour, or is this something beyond our control?

Tabline when holding `Alt` key, notice the underline under the letter `d` (caused by holding the `Alt` key):
![alt-hijacked](https://user-images.githubusercontent.com/11158705/32638991-b2f2f57c-c5fc-11e7-991e-6fb91efe72bb.png)

```
nvim: v0.2.1
nvim-qt: commit 0551ef29108ebcfad2f9bcaa8658317bf8ca886c
```

**Comment by equalsraf** [comment]
Strange I cannot reproduce with a buffer named `d`. I can however reproduce with a buffer named `&d` i.e.

1. `:tabnew`
2. `:e &d`

The `d` in the tabname should now be underscored and the issue can be triggered.

@qwfy Is there any reason why your tabs would be named `&cat` and `&dog`?

This is definitely not intentional. In fact I was under that assumption that this line prevented this issue

https://github.com/equalsraf/neovim-qt/blob/master/src/gui/mainwindow.cpp#L44

But having a closer look a the Qt docs 

> QTabBar creates automatic mnemonic keys in the manner of QAbstractButton; e.g. if a tab's label is "&Graphics", Alt+G becomes a shortcut key for switching to that tab.

I've pushed #358 to fix my case but I dont know if it fixes yours too. Can you have a look.

**Comment by qwfy** [comment]
Branch fix-357 didn't fix the problem.

> Is there any reason why your tabs would be named &cat and &dog?

No, I don't think they are named &cat and &dog, (but I cannot say for sure, I couldn't find a command to display the current tab's name): both `:echo &tabline` and `:echo &guitablabel` is empty, further more, I moved `~/.config/nvim/` to some other place and start with `nvim-qt -- --noplugin` to have a clean start, still can reproduce.

On 62d3976cb3cd59786df5c733cf299f8c25366263, both `:e d` and `:e &d` will hijack the Alt key.

**Comment by qwfy** [comment]
As pointed out [here](https://stackoverflow.com/questions/32688153/how-to-disable-automatic-mnemonics-in-a-qt-application-on-kde), adding

```
[Development]
AutoCheckAccelerators=false
```
to `~/.config/kdeglobals`, then invoke the usual `cmake ... make ...` build command solves the problem, but it turns the color of the title bar from black-ish to blue.

**Comment by equalsraf** [comment]
Ok so in your case this is a problem with kde the upstream bug is 

- https://bugs.kde.org/show_bug.cgi?id=337491 
- https://bugs.kde.org/show_bug.cgi?id=345023

and it seems to break keyboard shortcuts for multiple Qt applications. I have yet to find a way to work around it (other than the kdeglobals config).

> but it turns the color of the title bar from black-ish to blue.

The window titlebar? There is probably something you can do about it in kwin.

**Comment by qwfy** [comment]
A solution is given by one of the [comment](https://bugs.kde.org/show_bug.cgi?id=337491#c21), but I haven't tried it, don't know much about C++.

Yes, the window titlebar, but a reboot solves it, it's probably more economical to reboot than tracing down the cause, I can live with it.

**Comment by equalsraf** [comment]
> A solution is given by one of the comment, but I haven't tried it, don't know much about C++.

I've seen the comment but that is not a option for us.  That code

```c++
void Helpers::disableSystemAccel(QWidget *what)
{
    void *d = dlopen("libKF5WidgetsAddons.so", RTLD_LAZY);
    if (!d)
        return;
    typedef void (*DisablerFunc)(QWidget *);
    DisablerFunc setNoAccel;
    setNoAccel = reinterpret_cast<DisablerFunc>(dlsym(d, "_ZN19KAcceleratorManager10setNoAccelEP7QWidget"));
    if (setNoAccel)
        setNoAccel(what);
    dlclose(d);
}
```

opens one of the kde libraries at runtime to call a function to disable the accelerators. I have no intention of adding something like that. That cast from a mangled C++ symbol will likely not work for all kde versions or different systems. This is definitely a problem that needs to be fixed in KDE. If they provide a way to do this that does not involve linking against their libraries then I might consider it.
